# Generated by Django 2.2 on 2019-04-10 05:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_code', models.CharField(default=uuid.uuid4, max_length=1024, unique=True, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания кода подтверждения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('confirm', models.BooleanField(default=False, verbose_name='Подтвержден?')),
            ],
            options={
                'verbose_name': 'Подтверждение емейла',
                'verbose_name_plural': 'Подтверждение емейлов',
            },
        ),
    ]
