# Generated by Django 2.2 on 2019-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationemail',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
    ]
