# Generated by Django 2.2 on 2019-04-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
