# Generated by Django 2.2 on 2019-04-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Отчество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_users', to='blog_backend.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Данные пользователя заказа',
                'verbose_name_plural': 'Данные пользователей заказов',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tourist', to='blog_backend.OrderUser', verbose_name='Данные туриста')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourists', to='blog_backend.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='blog_backend.OrderUser', verbose_name='Заказчик'),
        ),
    ]
