# Generated by Django 2.2 on 2019-04-10 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Емейл')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default=None, max_length=12, null=True, verbose_name='Пол')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Отчество')),
                ('password', models.CharField(max_length=128, verbose_name='Проль')),
                ('date_birth', models.DateField(default=None, null=True, verbose_name='Дата рождения')),
                ('datetime_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регстрации')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ('-id',),
            },
        ),
    ]
